total:
  "大成功の年になることでしょう。"                           : :dai_kichi
  "幾度ものチャンスに恵まれる年になるでしょう。"             : :dai_kichi
  "活発な一年となるでしょう。"                               : :chu_kichi
  "心穏やかに過ごせる一年になるでしょう。"                   : :chu_kichi
  "素敵な一年となるでしょう。"                               : :sho_kichi
  "大きなトラブルもなく順調な一年となるでしょう。"           : :sho_kichi
  "期待に満ちた一年となるでしょう。"                         : :kichi
  "大きな転機が訪れる一年となるでしょう。"                   : :kichi
  "時期によって波がありますが結果的に良い年となるでしょう。" : :han_kichi
  "これからの人生のための準備の一年となるでしょう。"         : :han_kichi
  "雪解け前のような一年となるでしょう。"                     : :han_kichi
  "自己の成長の一年となるでしょう。"                         : :sue_kichi
  "ピンチがチャンスの一年となるでしょう。"                   : :sue_kichi
  "波瀾万丈な一年になるでしょう。"                           : :suesho_kichi
  "結果としては厳しい一年となるでしょう。"                   : :suesho_kichi
money:
  "無駄遣いは控えよ"   : :master
  "貯蓄に回すべし"     : :master
  "計画的に使え"       : :master
  "使うときには使え"   : :master
  "自己研鑚に使え"     : :master
  "半分を貯蓄に回せ"   : :master
  "ほどほどに使え"     : :master
  "使うな"             : :master
  "賢く使え"           : :master
  "じっくり考えて使え" : :master
  "後悔しないよう使え" : :master
health:
  "身体を鍛えろ"       : :master
  "風邪ひきやすし"     : :master
  "疲れがたまりやすい" : :master
  "健康に過ごせる"     : :master
  "腰を労れ"           : :master
  "肩を労れ"           : :master
  "胃腸を労れ"         : :master
  "甘いモノは控えよ"   : :master
  "塩分は控えよ"       : :master
love:
  "出会いあり"               : :dai_kichi
  "上々"                     : :dai_kichi
  "安定の一年"               : :chu_kichi
  "独り身なら想い人が現れる" : :chu_kichi
  "努力すれば成就する"       : :sho_kichi
  "チャンスがあれば逃がすな" : :kichi
  "決断が必要"               : :han_kichi
  "自分を磨くこと"           : :sue_kichi
  "待ちに徹するべし"         : :suesho_kichi
